# Generated by Django 5.0.6 on 2024-06-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_last_namr_customer_last_name_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
