# Generated by Django 5.0.6 on 2024-06-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_item',
            new_name='OrderItem',
        ),
    ]
