# Generated by Django 5.0.6 on 2024-06-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_order_item_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lastupdate',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
