# Generated by Django 5.0.6 on 2024-06-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_lastupdate_product_last_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='id',
        ),
    ]
